# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-31 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picnic', '0008_auto_20180127_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('profiles', models.ManyToManyField(to='picnic.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('picture', models.CharField(default='https://www.picnic.nl/shared-assets/images/public/img-logo@2x.png', max_length=500)),
                ('persons', models.IntegerField()),
                ('items', models.ManyToManyField(to='picnic.Item')),
            ],
        ),
        migrations.AddField(
            model_name='dinnerdate',
            name='recipes',
            field=models.ManyToManyField(to='dinner.Recipe'),
        ),
    ]
