# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-31 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerdate',
            name='day',
        ),
        migrations.AddField(
            model_name='dinnerdate',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
