# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0002_auto_20180131_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='items',
        ),
        migrations.AddField(
            model_name='recipe',
            name='foodtype',
            field=models.CharField(default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='link',
            field=models.CharField(default='https://www.ah.nl/allerhande', max_length=1000),
        ),
    ]
