# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-18 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0004_auto_20180518_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='forward_link',
            new_name='link',
        ),
    ]
