# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-22 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnic', '0009_profile_boodschap_stand'),
        ('dinner', '0005_auto_20180518_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerdate',
            name='boodschap_feuten',
            field=models.ManyToManyField(related_name='feuten', to='picnic.Profile'),
        ),
    ]
