# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0007_auto_20180922_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerdate',
            name='boodschap_feuten',
            field=models.ManyToManyField(blank=True, related_name='feuten', to='picnic.Profile'),
        ),
        migrations.AlterField(
            model_name='dinnerdate',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='picnic.Profile'),
        ),
        migrations.AlterField(
            model_name='dinnerdate',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='dinner.Recipe'),
        ),
    ]
