# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picnic', '0010_auto_20190302_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_description', models.CharField(max_length=500)),
                ('value', models.FloatField(default=1)),
                ('done', models.BooleanField(default=False)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='picnic.Profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='picnic.Profile')),
            ],
        ),
    ]
