# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-12 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetbekje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='target_won',
            field=models.BooleanField(default=True),
        ),
    ]
