# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-16 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetbekje', '0002_battle_target_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='ratio',
            field=models.FloatField(default=1),
        ),
    ]
