# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picnic', '0011_auto_20190312_2027'),
        ('vetbekje', '0003_battle_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='PoolEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picnic.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='entries',
            field=models.ManyToManyField(to='vetbekje.PoolEntry'),
        ),
    ]
