# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-17 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetbekje', '0004_auto_20190317_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pool',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pool',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='vetbekje.PoolEntry'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='entries',
            field=models.ManyToManyField(related_name='entries', to='vetbekje.PoolEntry'),
        ),
    ]
