# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-17 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picnic', '0011_auto_20190312_2027'),
        ('vetbekje', '0006_auto_20190317_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='picnic.Profile'),
            preserve_default=False,
        ),
    ]
