# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-17 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetbekje', '0007_pool_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='picnic.Profile'),
        ),
    ]
