# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-17 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetbekje', '0008_auto_20190317_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picnic.Profile'),
        ),
    ]
