# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picnic', '0005_auto_20171122_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilsbaas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picnic.Profile')),
            ],
        ),
    ]
