# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-22 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilsbazen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilsbaas',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Pilsbaas',
        ),
    ]
