# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-13 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picnic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='items',
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.CharField(default='https://www.picnic.nl/images/public/img-logo@2x.png', max_length=500),
        ),
        migrations.AddField(
            model_name='listitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='picnic.Item'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picnic.List'),
        ),
        migrations.AddField(
            model_name='listitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picnic.Profile'),
        ),
    ]
