# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-13 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picnic', '0002_auto_20171113_1510'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together=set([('item', 'profile', 'list')]),
        ),
    ]
