# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-13 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picnic', '0003_auto_20171113_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picnic.Item'),
        ),
    ]
