# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-22 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnic', '0004_auto_20171113_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
