# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnic', '0007_profile_turfjes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.CharField(default='https://www.picnic.nl/shared-assets/images/public/img-logo@2x.png', max_length=500),
        ),
    ]
