# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-22 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnic', '0008_auto_20180127_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='boodschap_stand',
            field=models.IntegerField(default=0),
        ),
    ]
