# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnic', '0009_profile_boodschap_stand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='boodschap_stand',
            field=models.FloatField(default=0),
        ),
    ]
