# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-12 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picnic', '0010_auto_20190302_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(default='images/anonymous.jpg', upload_to='images'),
        ),
    ]
